/* eslint-disable */
// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsmobile = {
    "aws_project_region": "us-east-1",
    "aws_cognito_identity_pool_id": "us-east-1:168188b8-1115-490b-b07d-760820366e0d",
    "aws_cognito_region": "us-east-1",
    "aws_user_pools_id": "us-east-1_aHJLZFQNN",
    "aws_user_pools_web_client_id": "6h87a5or5gjc84rce5m2bvkgp1",
    "oauth": {},
    "aws_appsync_graphqlEndpoint": "https://jfsbm5yfbza5re7ugtv7cfcnvy.appsync-api.us-east-1.amazonaws.com/graphql",
    "aws_appsync_region": "us-east-1",
    "aws_appsync_authenticationType": "AMAZON_COGNITO_USER_POOLS"
};


export default awsmobile;
